language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO_VERSION=1.6
    - DJANGO_VERSION=1.5
install:
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
script:
    - nosetests
    - python cstypo/parser.py -v
notifications:
    email: false
